# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "async-ruby-zip"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Grigoriy Chudnov"]
  s.date = "2012-08-04"
  s.description = "Non-blocking zip reading and writing for Ruby."
  s.email = "g.chudnov@gmail.com"
  s.extensions = ["ext/extconf.rb"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile.lock",
    "README.md",
    "async-ruby-zip-1.0.0.gem",
    "async-ruby-zip.gemspec",
    "ext/LICENSE",
    "ext/archive.c",
    "ext/archive.h",
    "ext/archive_data.c",
    "ext/archive_data.h",
    "ext/archive_data_fwd.h",
    "ext/async_zip.c",
    "ext/async_zip.h",
    "ext/callback.c",
    "ext/callback.h",
    "ext/carchive.c",
    "ext/carchive.h",
    "ext/carray.c",
    "ext/carray.h",
    "ext/cerror.c",
    "ext/cerror.h",
    "ext/cfilesystem.c",
    "ext/cfilesystem.h",
    "ext/extconf.rb",
    "ext/task.c",
    "ext/task.h",
    "ext/writer.c",
    "ext/writer.h",
    "lib/async_zip.rb",
    "lib/async_zip/version.rb"
  ]
  s.homepage = "https://github.com/gchudnov/async-ruby-zip"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "async-ruby-zip is a ruby extension that zip files asynchronously."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rdoc>, "~> 6.3")
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rdoc>, "~> 6.3")
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rdoc>, "~> 6.3")
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

